# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Terrain4aAVR
                                 A QGIS plugin
 Outputs 300km square terrain data for arcAstroVR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-12
        copyright            : (C) 2022 by Kuninori Iwashiro (scienceNODE)
        email                : iwashiro@science-node.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Terrain4aAVR class from file Terrain4aAVR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .terrain4aAVR import Terrain4aAVR
    return Terrain4aAVR(iface)
